### ISSUE TITLE
Mediator得票数改为带小数的形式

### ISSUE THREAD

**Issue by studyzy** [studyzy/wallet#16]
以1PTN 1票的原则，在得票数显示的时候，应该除以10^8,显示小数形式的票数。

**Comment by studyzy** [comment]
参考：https://palletone.info/viewMediator

**Comment by studyzy** [comment]
Mediator列表的票数已经改为小数，但是点进某个详情时，还是大整数。 @kester001122

**Comment by kester001122** [comment]
已经改好了
