### ISSUE TITLE
增发地址为空时，721类型被A地址增发一次后，B地址增发时提示 地址无增发权

### ISSUE THREAD

**Issue by elva1087** [studyzy/wallet#4]
1. 721增发地址为空，任何地址都可以增发 N
2. 20是必须增发地址能增发，为空就不能增发 Y

**Comment by elva1087** [comment]
Android 版本 PRC20增发地址目前为必填项，逻辑与上溯不符，待新版验证

**Comment by elva1087** [comment]
Androi 721创建提示: 执行失败，阻塞复测

**Comment by kester001122** [comment]
已解决  请重试

**Comment by kester001122** [comment]
糟了 点错了 按钮

**Comment by elva1087** [comment]
Andrord PRC20 发行有一定几率 发行失败

**Comment by kester001122** [comment]
不可避免的失败是可能的，就是操作太快
